INSERT INTO AUTHOR VALUES (1,SYSDATE - 1 ,'ELDO');
INSERT INTO AUTHOR VALUES (2,SYSDATE - 2 ,'RAM');
INSERT INTO AUTHOR VALUES (3,SYSDATE - 3 ,'JAMES');
INSERT INTO AUTHOR VALUES (4,SYSDATE - 4 ,'ROAST');
INSERT INTO AUTHOR VALUES (5,SYSDATE - 5 ,'CAST');
INSERT INTO AUTHOR VALUES (6,SYSDATE - 6 ,'DAVID');
INSERT INTO AUTHOR VALUES (7,SYSDATE - 7 ,'RAKESH');
INSERT INTO AUTHOR VALUES (8,SYSDATE - 8 ,'SATISH');
INSERT INTO AUTHOR VALUES (9,SYSDATE - 9 ,'PRAKASH');
INSERT INTO AUTHOR VALUES (10,SYSDATE - 10 ,'MAHI');


INSERT INTO MESSAGE VALUES (20,SYSDATE,1,'Hello 1',1);
INSERT INTO MESSAGE VALUES (21,SYSDATE - 1,1,'Hello 2',2);
INSERT INTO MESSAGE VALUES (22,SYSDATE - 2,1,'Hello 3',3);
INSERT INTO MESSAGE VALUES (23,SYSDATE - 3,1,'Hello 4',4);
INSERT INTO MESSAGE VALUES (24,SYSDATE - 4,1,'Hello 5',5);
INSERT INTO MESSAGE VALUES (25,SYSDATE - 5,1,'Hello 6',6);
INSERT INTO MESSAGE VALUES (26,SYSDATE - 6,1,'Hello 7',7);
INSERT INTO MESSAGE VALUES (27,SYSDATE - 7,1,'Hello 8',8);
INSERT INTO MESSAGE VALUES (28,SYSDATE - 8,1,'Hello 9',9);
INSERT INTO MESSAGE VALUES (29,SYSDATE - 9,1,'Hello 10',10);
INSERT INTO MESSAGE VALUES (30,SYSDATE - 10,1,'Hello 11',1);
